name: Vim_Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vim:
        - v8.2.0000
        - v8.1.0000
        - v8.0.0000
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Vim
      uses: rhysd/action-setup-vim@v1
      id: vim
      with:
        version: ${{ matrix.vim }}
    - name: Test
      run: | 
       echo "set runtimepath+=$GITHUB_WORKSPACE" > $HOME/.vimrc
       vim --version
       vim +":call Weather#test#run()"
